# https://github.com/DavidAnson/markdownlint/blob/v0.37.3/schema/.markdownlint.yaml

# MD013/line-length : Line length : https://github.com/DavidAnson/markdownlint/blob/v0.37.3/doc/md013.md
MD013: false
